"""Generate standardised report figures from committed data and outputs.

Every figure is written to ``report/figures`` as PNG at a consistent style.
Figures whose inputs are missing (for example, the market-making study
artifacts, which are generated by a heavier script) are skipped with a note.
The script is deterministic for figures computed from recorded values; the
C++ speedup figure measures a short local benchmark when the backend exists.
"""

from __future__ import annotations

import json
import math
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.volatility_surface.calibration import calibrate_svi
from src.volatility_surface.svi import svi_total_variance

FIGURES = PROJECT_ROOT / "report" / "figures"
FIGURES.mkdir(parents=True, exist_ok=True)

plt.rcParams.update(
    {
        "figure.dpi": 160,
        "savefig.dpi": 160,
        "font.size": 10,
        "axes.titlesize": 12,
        "axes.labelsize": 10,
        "legend.fontsize": 9,
        "axes.grid": True,
        "grid.alpha": 0.3,
    }
)


def save(figure, name: str) -> None:
    path = FIGURES / name
    figure.savefig(path, bbox_inches="tight")
    plt.close(figure)
    print(f"saved {path.relative_to(PROJECT_ROOT)}")


def load_evidence() -> dict:
    path = PROJECT_ROOT / "outputs" / "evidence_20260904.json"
    if not path.exists():
        raise FileNotFoundError(str(path))
    return json.loads(path.read_text(encoding="utf-8"))


def pricing_convergence() -> None:
    evidence = load_evidence()
    crr = {
        int(steps): error
        for steps, error in evidence["pricing_convergence"][
            "crr_absolute_error"
        ].items()
    }
    fd = evidence["pricing_convergence"][
        "crank_nicolson_absolute_error"
    ]["400"]
    steps = sorted(crr)
    figure, axis = plt.subplots(figsize=(7.5, 4.6))
    axis.plot(steps, [crr[s] for s in steps], "o-", label="CRR binomial")
    axis.scatter([400], [fd], marker="s", color="tab:red", label="Crank-Nicolson")
    axis.set_xscale("log", base=2)
    axis.set_yscale("log")
    axis.set_xticks(steps)
    axis.set_xticklabels([str(s) for s in steps])
    axis.set_xlabel("Steps")
    axis.set_ylabel("Absolute error vs Black-Scholes")
    axis.set_title("Numerical convergence to Black-Scholes (S=100, K=100, T=0.5)")
    axis.legend()
    save(figure, "pricing_convergence.png")


def degeneracy_validation() -> None:
    from src.domain.enums import OptionType
    from src.pricing.black_scholes import option_price
    from src.pricing.heston import (
        heston_mc_price,
        heston_price_semi_analytic,
    )
    from src.pricing.merton import merton_series_price

    bs = option_price(
        spot=100.0,
        strike=100.0,
        time_to_expiry=0.5,
        risk_free_rate=0.04,
        volatility=0.2,
        option_type="call",
        dividend_yield=0.0,
    )
    merton_error = abs(
        merton_series_price(
            100.0,
            100.0,
            0.5,
            0.2,
            0.04,
            OptionType.CALL,
            jump_intensity=0.0,
            jump_mean=0.0,
            jump_vol=0.0,
        )
        - bs
    )
    heston_error = abs(
        heston_price_semi_analytic(
            100.0,
            100.0,
            0.5,
            1.0,
            0.04,
            1e-9,
            0.0,
            0.04,
            0.04,
            OptionType.CALL,
            0.0,
        )
        - bs
    )
    labels = ["Merton series -> BS", "Heston semi-analytic -> BS"]
    errors = [merton_error, heston_error]
    figure, axis = plt.subplots(figsize=(7.0, 4.4))
    bars = axis.bar(labels, [max(e, 1e-12) for e in errors], color=["tab:blue", "tab:green"])
    axis.set_yscale("log")
    axis.set_ylabel("Absolute error")
    axis.set_title("Degeneracy validation (limit parameters)")
    for bar, error in zip(bars, errors):
        axis.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() * 1.6,
            f"{error:.2e}",
            ha="center",
            va="bottom",
            fontsize=9,
        )
    save(figure, "degeneracy_validation.png")


def svi_surface() -> None:
    path = PROJECT_ROOT / "outputs" / "real_option_chain" / "spy_option_chain_active.csv"
    frame = pd.read_csv(path, parse_dates=["expiry"])
    figure, axes = plt.subplots(
        1,
        2,
        figsize=(11.5, 4.8),
        gridspec_kw={"width_ratios": [2.4, 1.0]},
    )
    for expiry, group in frame.groupby(frame["expiry"].dt.date):
        rows = group.dropna(subset=["iv"])
        rows = rows[rows["iv"] > 0]
        k = rows["log_moneyness"].to_numpy()
        w = (rows["iv"] ** 2 * rows["time_to_expiry"]).to_numpy()
        if len(k) < 5:
            continue
        params = calibrate_svi(k, w, minimum_points=5).parameters
        model = svi_total_variance(
            k,
            params["a"],
            params["b"],
            params["rho"],
            params["m"],
            params["sigma"],
        )
        order = np.argsort(k)
        axes[0].plot(k[order], model[order], "-", lw=1.6)
        axes[0].scatter(k, w, s=8, alpha=0.55)
        rmse = float(np.sqrt(np.mean((model - w) ** 2)))
        axes[1].scatter(k, w - model, s=8, alpha=0.55, label=f"{expiry} rmse={rmse:.1e}")
    axes[0].set_xlabel("log-moneyness k")
    axes[0].set_ylabel("Total variance w")
    axes[0].set_title("SVI fit vs market total variance (per expiry)")
    axes[1].set_xlabel("log-moneyness k")
    axes[1].set_ylabel("Residual w - SVI")
    axes[1].set_title("Fit residuals")
    axes[1].legend(fontsize=7)
    save(figure, "svi_surface.png")


def _equity_plot(source: str) -> None:
    frame = pd.read_csv(source, parse_dates=["date"])
    figure, axes = plt.subplots(
        2,
        1,
        figsize=(9.0, 6.0),
        sharex=True,
        gridspec_kw={"height_ratios": [2.0, 1.0]},
    )
    axes[0].plot(frame["date"], frame["equity"], lw=1.8)
    axes[0].set_ylabel("Equity")
    axes[0].set_title(f"Equity and drawdown ({Path(source).name})")
    axes[1].plot(frame["date"], frame["drawdown_pct"] * 100.0, lw=1.4, color="tab:red")
    axes[1].set_ylabel("Drawdown (%)")
    axes[1].set_xlabel("Date")
    figure.autofmt_xdate()
    save(figure, Path(source).stem + ".png")


def backtest_figures() -> None:
    rolling = (
        PROJECT_ROOT / "outputs" / "rolling_backtest"
        / "spy_rolling_long_straddle_equity_curve.csv"
    )
    if rolling.exists():
        _equity_plot(str(rolling))

    baseline = (
        PROJECT_ROOT / "outputs" / "volatility_filtered_backtest"
        / "baseline_equity_curve.csv"
    )
    filtered = (
        PROJECT_ROOT / "outputs" / "volatility_filtered_backtest"
        / "volatility_filtered_equity_curve.csv"
    )
    if baseline.exists() and filtered.exists():
        base = pd.read_csv(baseline, parse_dates=["date"])
        filt = pd.read_csv(filtered, parse_dates=["date"])
        figure, axis = plt.subplots(figsize=(9.0, 4.8))
        axis.plot(base["date"], base["equity"], lw=1.6, label="No filter (33 trades)")
        axis.plot(filt["date"], filt["equity"], lw=1.8, label="Regime filter (11 trades)")
        axis.set_xlabel("Date")
        axis.set_ylabel("Equity")
        axis.set_title("Long-straddle rolling backtest: baseline vs volatility filter")
        axis.legend()
        figure.autofmt_xdate()
        save(figure, "volatility_filter_comparison.png")


def hedging_sensitivity() -> None:
    source = (
        PROJECT_ROOT / "outputs" / "sensitivity"
        / "hedging_sensitivity_results.csv"
    )
    if not source.exists():
        print("skip hedging_sensitivity: file missing")
        return
    frame = pd.read_csv(source)
    grouped = frame.groupby("delta_threshold").agg(
        final_pnl=("final_pnl", "mean"),
        hedge_costs=("cumulative_hedge_costs", "mean"),
        hedge_trades=("number_of_hedge_trades", "mean"),
    )
    figure, axis = plt.subplots(figsize=(8.2, 4.8))
    axis.plot(grouped.index, grouped["final_pnl"], "o-", label="Mean final PnL")
    axis.set_xlabel("Delta hedge threshold")
    axis.set_ylabel("Mean final PnL", color="tab:blue")
    axis.tick_params(axis="y", labelcolor="tab:blue")
    twin = axis.twinx()
    twin.bar(grouped.index, grouped["hedge_costs"], alpha=0.35, color="tab:red", label="Mean hedge costs")
    twin.set_ylabel("Mean cumulative hedge costs", color="tab:red")
    twin.tick_params(axis="y", labelcolor="tab:red")
    lines, labels = axis.get_legend_handles_labels()
    lines2, labels2 = twin.get_legend_handles_labels()
    axis.legend(lines + lines2, labels + labels2, loc="best")
    axis.set_title("Hedging threshold sensitivity: PnL vs transaction costs")
    save(figure, "hedging_cost_sensitivity.png")


def var_backtest() -> None:
    price_path = PROJECT_ROOT / "data" / "raw" / "spy_daily_adjusted.csv"
    frame = pd.read_csv(price_path, parse_dates=["Date"]).set_index("Date")
    returns = frame["Close"].pct_change().dropna()
    rolling_var = (
        -returns.rolling(60)
        .apply(lambda x: np.quantile(x, 0.05), raw=True)
        .shift(1)
    )
    window = returns.iloc[60:]
    valid = pd.concat([window, rolling_var.loc[window.index]], axis=1).dropna()
    valid.columns = ["pnl", "var"]
    breaches = valid["pnl"] < -valid["var"]
    figure, axis = plt.subplots(figsize=(10.0, 4.6))
    axis.plot(valid.index, valid["pnl"], lw=0.5, label="Daily PnL")
    axis.plot(valid.index, -valid["var"], lw=1.0, color="tab:red", label="-95% VaR")
    axis.scatter(
        valid.index[breaches],
        valid["pnl"][breaches],
        s=18,
        color="black",
        label=f"Breaches ({int(breaches.sum())})",
        zorder=5,
    )
    axis.set_xlabel("Date")
    axis.set_ylabel("Daily return")
    axis.set_title("SPY 95% rolling historical VaR backtest (60-day window)")
    axis.legend()
    figure.autofmt_xdate()
    save(figure, "var_backtest_breaches.png")


def cpp_speedup() -> None:
    baseline_path = PROJECT_ROOT / "outputs" / "testing" / "benchmark_baseline.json"
    if not baseline_path.exists():
        print("skip cpp_speedup: benchmark_baseline.json missing")
        return
    baseline = json.loads(baseline_path.read_text(encoding="utf-8"))
    if not baseline.get("backend_available"):
        print("skip cpp_speedup: backend unavailable")
        return
    python_seconds = baseline["python_seconds"]
    cpp_seconds = baseline["cpp_seconds"]
    speedup = baseline["speedup"]
    figure, axis = plt.subplots(figsize=(6.8, 4.4))
    bars = axis.bar(
        ["Python scalar", "C++ batch"],
        [python_seconds, cpp_seconds],
        color=["tab:blue", "tab:green"],
    )
    axis.set_ylabel("Seconds (1,000,000 prices)")
    axis.set_title(f"C++ batch kernel vs Python scalar loop: {speedup:.1f}x")
    for bar, seconds in zip(bars, [python_seconds, cpp_seconds]):
        axis.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() * 1.02,
            f"{seconds:.3f}s",
            ha="center",
            va="bottom",
        )
    axis.set_ylim(0, python_seconds * 1.2)
    save(figure, "cpp_speedup.png")


def main() -> None:
    start = time.perf_counter()
    pricing_convergence()
    degeneracy_validation()
    svi_surface()
    backtest_figures()
    hedging_sensitivity()
    var_backtest()
    cpp_speedup()
    print(f"done in {time.perf_counter() - start:.1f}s")


if __name__ == "__main__":
    main()
